### ISSUE TITLE
All books stored in a simple array

### ISSUE THREAD

**Issue by fabricio-garcia** [fabricio-garcia/library#1]
**Tasks**

- [x] All of the book objects are going to be stored in a simple array
- [x] An add function is needed in the script (not the constructor) that can take user’s input and store the new book objects into an array. 
- [x] Your code should look something like this:

```
let myLibrary = [];

function Book() {
  // the constructor...
}

function addBookToLibrary() {
  // do stuff here
} 
```

**Tests**

- [x] It should be an array called myLibrary
- [x] It should be function that  can take user’s input and store the new book objects into an array. 
- [x] Check for title, author, number of pages, status

**Reference**

[The Odin Project](https://www.theodinproject.com/courses/javascript/lessons/library)

**Comment by Israel-Laguan** [comment]
In the constructor I think we need something like this:

```js
function Book (name, title, pages, read) {
    this.name = name;
    this.title = title;
    this.pages = pages;
    this.read = read;
};

```

**Comment by fabricio-garcia** [comment]
We can start off using that function and the modify it later in case it is required.

**Comment by Israel-Laguan** [comment]
About the data I suggest:

-  this.name String;
-  this.title String;
-  this.pages Number;
-  this.read Boolean;

Also the Array must have just Instances of Book, or maybe just Objects with State? 

What do you think @fabricio-garcia ?

**Comment by Israel-Laguan** [comment]
Also we need to think about folder/files structure. i suggest inside of `src/`:
```
src
  - js
    + Library
       * readAll.js
       * create.js
       * erase.js
    + index.js
    + external.js
```
What do you think?

**Comment by fabricio-garcia** [comment]
Regarding the folder structure in general I suggest a simpler approach since this is a small project, something like this:
```
app
  fonts
  images
  scripts
  styles
test
  spec
```

**Comment by Israel-Laguan** [comment]
About app/ we have src/ , should we change name ?

**Comment by Israel-Laguan** [comment]
So you want to use one one file for all the project?

**Comment by fabricio-garcia** [comment]
sure we can change src instead or app

**Comment by fabricio-garcia** [comment]
> So you want to use one one file for all the project?

That's a better approach for a small project

**Comment by Israel-Laguan** [comment]
If the file js is bigger than 100 LOC its ok for you to cut it in 2 or more files?

**Comment by fabricio-garcia** [comment]
> If the file js is bigger than 100 LOC its ok for you to cut it in 2 or more files? @fabricio-garcia

I agree with that

**Comment by Israel-Laguan** [comment]
We already tests these

![image](https://user-images.githubusercontent.com/36519478/73283940-d10cec00-41c1-11ea-9081-4040f0362866.png)

**Comment by fabricio-garcia** [comment]
Created a testing file for test cases in test/issue1.js.
All tasks are now implemented.
