### ISSUE TITLE
Array hooked up to HTML with render()

### ISSUE THREAD

**Issue by Israel-Laguan** [fabricio-garcia/library#2]
# Task

Create views to represent the books on the library.

Put all the views on `render()` function with a List that have all the Books.

# Test

- [x] You must be capable of read all the books in an arrays or an object
- [x] The list must be accessible on a render function
- [x] The render function will create HTML to list the book

**Comment by Israel-Laguan** [comment]
I think that for the views we must divide info templates like this 

https://css-tricks.com/html-templates-via-javascript-template-literals/

That way we can something like this on render():

```
let book1 = createBook('My title', 'My Author', 25, false);
let List = document.getElementById('library-list');
list.appendChild(book1);
```
Because book1 would be already a string for use on HTML

**Comment by fabricio-garcia** [comment]
It looks convenient for this project. We can go ahead an use it.

**Comment by fabricio-garcia** [comment]
All tasks and tests are implemented now

![captura_1](https://user-images.githubusercontent.com/9059238/73297866-f43f9780-41d1-11ea-91cb-9abf414f4cc1.png)

![captura_2](https://user-images.githubusercontent.com/9059238/73297882-f9044b80-41d1-11ea-8163-c55c407b03b6.png)
