### ISSUE TITLE
Display books in a table, card, etc.

### ISSUE THREAD

**Issue by Israel-Laguan** [fabricio-garcia/library#3]
# Task

- [x] Each book must be displayed inside the list (maybe we have to limit the number of books showed? Like if we have 10000+ would be hard to show them in a list)
- [x] It must read the title, author, pages and if is already read

**Comment by Israel-Laguan** [comment]
So @fabricio-garcia  want to use a table instead of cards, is correct?

**Comment by fabricio-garcia** [comment]
Correct, presenting the information in a table saves us some space to present the information to the user.

**Comment by Israel-Laguan** [comment]
![image](https://user-images.githubusercontent.com/36519478/73329277-0ef22a80-422b-11ea-90ad-a5dac67dbea3.png)

- [x] List is displayed
- [x] Change is displayed

**Comment by Israel-Laguan** [comment]
Erased the Tests part so the issue can be closed.
