### ISSUE TITLE
Add a "NEW BOOK" button that brings up a form allowing users to input the book details.

### ISSUE THREAD

**Issue by Israel-Laguan** [fabricio-garcia/library#4]
# Task

- [x] The user must be capable of add a new book using the view
- [x] The book list must have a button or something to add the book (maybe a form?)
- [x] When you fill the info needed we can add validations
- [x] The change can be done intermediately or we need to refresh?

**Comment by Israel-Laguan** [comment]
For the add you wanted a form above the table with all books, right? @fabricio-garcia

**Comment by Israel-Laguan** [comment]
How we ensure that when a new book is added it appears immediately?

**Comment by fabricio-garcia** [comment]
> For the add you wanted a form above the table with all books, right? @fabricio-garcia
The form should be on top, the list below.

**Comment by Israel-Laguan** [comment]
# View
Added the form
![image](https://user-images.githubusercontent.com/36519478/73327338-8fad2880-4223-11ea-8d75-15a33637d345.png)

# Validations
-[x] Empty library
![image](https://user-images.githubusercontent.com/36519478/73328410-a5245180-4227-11ea-9197-429f42f66081.png)

- [x] empty title or author
![image](https://user-images.githubusercontent.com/36519478/73328421-b705f480-4227-11ea-82ca-b7a974ad27f7.png)

- [x] Incorrect format for title or author
![image](https://user-images.githubusercontent.com/36519478/73328501-051af800-4228-11ea-9153-ef35ec131000.png)

# Add Button works:
![image](https://user-images.githubusercontent.com/36519478/73328541-30054c00-4228-11ea-8a0d-8db0e367b512.png)

![image](https://user-images.githubusercontent.com/36519478/73328552-3a274a80-4228-11ea-9bd7-1e931dd195b4.png)

**Comment by Israel-Laguan** [comment]
Erased the Tests part so the issue can be closed.
