### ISSUE TITLE
Add a button on each book’s display to remove the book from the library.

### ISSUE THREAD

**Issue by Israel-Laguan** [fabricio-garcia/library#5]
# Task

- [x] Add a button to remove books
- [x] Be sure the button actually remove the book
- [x] Maybe we need to refresh or the change will come immediately?

**Comment by Israel-Laguan** [comment]
How we ensure that the erased book is retired immediately, or we don't have to show the change?

**Comment by fabricio-garcia** [comment]
> How we ensure that the erased book is retired immediately, or we don't have to show the change?

We can print a message in the screen telling the user the book was erased.

**Comment by Israel-Laguan** [comment]
I found that we need to identify each book by some mean, we can't rely in find by Tittle or author. So I Added a ISBN field
![image](https://user-images.githubusercontent.com/36519478/73371681-04b04a80-4284-11ea-835a-dbc0c2b59c25.png)

**Comment by Israel-Laguan** [comment]
I found that we need to identify each book by some mean, we can't rely on finding by Tittle or author. So I Added an ISBN field

**Comment by Israel-Laguan** [comment]
Erased the Tests part so the issue can be closed.
