### ISSUE TITLE
Add a button on each book’s display to change its read status.

### ISSUE THREAD

**Issue by Israel-Laguan** [fabricio-garcia/library#6]
# Task

- [x] There should be a button or checkbox for change the state form No read to read
- [x] The button must really change the array
- [x] The change must be noticeable in some way, like changing colors or something

**Comment by Israel-Laguan** [comment]
Do we use a Button or a checkbox?

To me the Checkbox is like more natural,

What do you think? @fabricio-garcia

**Comment by fabricio-garcia** [comment]
Either way should work just fine. We can try and determine what is ore suitable while testing it out.

**Comment by Israel-Laguan** [comment]
I think checkbox feels more natural, lets try checkbox first

**Comment by Israel-Laguan** [comment]
Here are some resources on Checkbox:

https://www.w3schools.com/tags/att_input_type_checkbox.asp

https://www.w3schools.com/tags/att_input_checked.asp

https://www.w3schools.com/howto/howto_js_display_checkbox_text.asp

**Comment by Israel-Laguan** [comment]
Erased the Tests part so the issue can be closed.
