### ISSUE TITLE
Optional: Store data 

### ISSUE THREAD

**Issue by Israel-Laguan** [fabricio-garcia/library#7]
# Task

- [x] You must save data on LocalStorage
- [x] ~You can use firestore to save data instead~ We decided to use just localStorage
- [x] Be sure to change internal code to grab the data from these storages, not the array

**Comment by Israel-Laguan** [comment]
I think that its enough with localStorage, maybe later we try Firebase, in another project, what do you think @fabricio-garcia

**Comment by fabricio-garcia** [comment]
It really relies in the time assigned and spent in the project. We can give it a try to Firebase in case we have some time left.

**Comment by Israel-Laguan** [comment]
About local Storage I left here some resources:

https://www.taniarascia.com/how-to-use-local-storage-with-javascript/

https://www.w3schools.com/html/html5_webstorage.asp

https://www.w3schools.com/jsref/prop_win_localstorage.asp

https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by Israel-Laguan** [comment]
Basicale is:
```
localStorage.setItem('key', 'value');
var cat = localStorage.getItem('key');
localStorage.removeItem('key');
```

**Comment by Israel-Laguan** [comment]
Erased the Tests part so the issue can be closed.
